// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvQnRWe1yrQXZm3kiZqUBEKoHhzkigLmA',
    appId: '1:217536032516:web:380b7362db762021c2aa51',
    messagingSenderId: '217536032516',
    projectId: 'device-streaming-76079634',
    authDomain: 'device-streaming-76079634.firebaseapp.com',
    storageBucket: 'device-streaming-76079634.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHaSUyBq2zmIXPIIMSz0KuD8a5WIhqTU8',
    appId: '1:217536032516:android:022fda9e3e0578bfc2aa51',
    messagingSenderId: '217536032516',
    projectId: 'device-streaming-76079634',
    storageBucket: 'device-streaming-76079634.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgHrP_Cf33n3Cp3MKPEKt97Jn9ATXz8Ag',
    appId: '1:217536032516:ios:6a3c6bd6658aa015c2aa51',
    messagingSenderId: '217536032516',
    projectId: 'device-streaming-76079634',
    storageBucket: 'device-streaming-76079634.firebasestorage.app',
    iosClientId: '217536032516-ubk2upj6plkul0dr4h9cpb0p0ppp3mv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgHrP_Cf33n3Cp3MKPEKt97Jn9ATXz8Ag',
    appId: '1:217536032516:ios:6a3c6bd6658aa015c2aa51',
    messagingSenderId: '217536032516',
    projectId: 'device-streaming-76079634',
    storageBucket: 'device-streaming-76079634.firebasestorage.app',
    iosClientId: '217536032516-ubk2upj6plkul0dr4h9cpb0p0ppp3mv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvQnRWe1yrQXZm3kiZqUBEKoHhzkigLmA',
    appId: '1:217536032516:web:09ce7bc9fe7ca110c2aa51',
    messagingSenderId: '217536032516',
    projectId: 'device-streaming-76079634',
    authDomain: 'device-streaming-76079634.firebaseapp.com',
    storageBucket: 'device-streaming-76079634.firebasestorage.app',
  );

}